messages:
  start: "&cСтример &f{player} &cначал стрим: &9&n{link}{desc}"
  desc: " &7({desc})"
  stop: "&aСтрим завершён!"
  no_permission: "&cУ вас нет прав на использование этой команды!"
  not_streaming: "&eВы не находитесь в эфире."
  need_link: "&eУкажите ссылку на твич: /стрим <ссылка>"
  usage: "&eИспользуйте: /стрим <ссылка> или /стрим стоп"
  only_player: "&cТолько игрок может использовать эту команду!"
  invalid_link: "&cВведите корректную ссылку на Twitch!"
  show_streamer: "§aTwitch канал §f{desc}: §9§n{link}"
  streamer_not_found: "§cСтример не найден!"
  streamer_added: "§aСтример {player} (Twitch: {desc}) добавлен!"
  no_add_permission: "§cУ вас нет прав на добавление стримеров!"
  no_remove_permission: "§cУ вас нет прав на удаление стримеров!"
  streamer_removed: "§aСтример {player} удалён!"
  streamer_list_header: "Список стримеров"
  streamer_list_entry: "§b• §a{player} §7(§5Twitch: {desc}§7) §9§n{link}"
  no_reload_permission: "§cУ вас нет прав на перезагрузку!"
  reload_success: "§aКонфиг Twitch перезагружен!"
  streamer_status_online: "§aСтример {player} сейчас В ЭФИРЕ!"
  streamer_status_offline: "§eСтример {player} сейчас оффлайн."
  stream_start_broadcast: "§d[СТРИМ] §a{player} начал стрим §d{desc}: "

twitch:
  # группа, которая выдается стримеру, когда он на стриме
  group: "twitch_on"
  # ID клиента Twitch
  client_id: "gp762nuuoqcoxypju8c569th9wz7q5"
  # Токен OAuth
  oauth_token: "677drltd2puo275xrt04d7jnvw4iv3"
  streamers: []
