name: TwitchStream
main: twitch.TwitchStreamPlugin
version: 1.0
api-version: 1.21
commands:
  стрим:
    description: Управление стримом на Twitch
    usage: |
      /стрим <ник> - показать Twitch-ссылку стримера (доступно всем)
      /стрим <ссылка> [описание] - начать стрим
      /стрим стоп - остановить стрим
      /стрим добавить <mc_ник> <twitch_ник> <ссылка> - добавить стримера (админ)
      /стрим удалить <mc_ник> - удалить стримера (админ)
      /стрим список - список стримеров
      /стрим статус <twitch_ник> - статус стримера
      /стрим reload - перезагрузка конфига (админ)

folia-supported: true
